//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AzuxServer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sale
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sale()
        {
            this.Payment = new HashSet<Payment>();
            this.ProductEntry = new HashSet<ProductEntry>();
            this.ScrapEntry = new HashSet<ScrapEntry>();
        }
    
        public int Id { get; set; }
        public int BillingAddressId { get; set; }
        public Nullable<int> ShippingAddressId { get; set; }
        public System.DateTime SaleTime { get; set; }
        public bool IsReverseCharge { get; set; }
        public decimal CashDiscountAmount { get; set; }
        public decimal RoundOffAmount { get; set; }
        public int TaxId { get; set; }
        public string TransportNode { get; set; }
        public string VehicleNumber { get; set; }
        public int TransportModeId { get; set; }
    
        public virtual Address Address { get; set; }
        public virtual Address Address1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Payment> Payment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductEntry> ProductEntry { get; set; }
        public virtual Tax Tax { get; set; }
        public virtual TransportMode TransportMode { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ScrapEntry> ScrapEntry { get; set; }
    }
}
